services:
  db:
    image: postgres:18.3
    container_name: ebsar-app-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ebsar
      POSTGRES_USER: ebsar
      POSTGRES_PASSWORD: ebsar@123
